spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: microcloud-config-server-dev

---
spring:
  profiles: beta
  application:
    name: microcloud-config-server-beta

---
spring:
  profiles: product
  application:
    name: microcloud-config-server-product